export const ITEMS_FETCH_DATA_SUCCESS = "ITEMS_FETCH_DATA_SUCCESS";
export const ITEMS_CATEGORY_DATA_SUCCESS = "ITEMS_CATEGORY_DATA_SUCCESS";
export const BANNER_DATA_SUCCESS = "BANNER_DATA_SUCCESS";
export const CART_ITEM_SUCCESS = "CART_ITEM_SUCCESS";
export const CART_OPEN_SUCCESS = "CART_OPEN_SUCCESS";
